import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

import { canvasThemes } from "@/lib/canvas-theme";

const neutral = {
    light: {
        brand: canvasThemes.light.node.accent,
        brandHover: "#9a3412",
        brandActive: "#7c2d12",
        onBrand: "#ffffff",
        layoutBg: canvasThemes.light.canvas.background,
        containerBg: canvasThemes.light.node.panel,
        elevatedBg: canvasThemes.light.node.panel,
        border: canvasThemes.light.node.stroke,
        borderSecondary: canvasThemes.light.node.fill,
        text: canvasThemes.light.node.text,
        textSecondary: canvasThemes.light.node.label,
        textTertiary: canvasThemes.light.node.muted,
        error: canvasThemes.light.node.danger,
        success: canvasThemes.light.node.success,
        warning: canvasThemes.light.node.warning,
        info: canvasThemes.light.node.info,
        itemHoverBg: canvasThemes.light.canvas.selectionFill,
        itemSelectedBg: canvasThemes.light.node.accentSoft,
        itemSelectedHoverBg: "#f7ddcd",
        itemText: canvasThemes.light.node.text,
        itemSelectedText: canvasThemes.light.node.accentText,
        tableSelectedBg: canvasThemes.light.node.accentSoft,
        tableSelectedHoverBg: "#f7ddcd",
    },
    dark: {
        brand: canvasThemes.dark.node.accent,
        brandHover: "#fdba74",
        brandActive: "#fed7aa",
        onBrand: "#1e1c19",
        layoutBg: canvasThemes.dark.canvas.background,
        containerBg: canvasThemes.dark.node.panel,
        elevatedBg: canvasThemes.dark.node.fill,
        border: canvasThemes.dark.node.stroke,
        borderSecondary: canvasThemes.dark.node.fill,
        text: canvasThemes.dark.node.text,
        textSecondary: canvasThemes.dark.node.label,
        textTertiary: canvasThemes.dark.node.muted,
        error: canvasThemes.dark.node.danger,
        success: canvasThemes.dark.node.success,
        warning: canvasThemes.dark.node.warning,
        info: canvasThemes.dark.node.info,
        itemHoverBg: canvasThemes.dark.canvas.selectionFill,
        itemSelectedBg: canvasThemes.dark.node.accentSoft,
        itemSelectedHoverBg: "rgba(251,146,60,.24)",
        itemText: canvasThemes.dark.node.text,
        itemSelectedText: canvasThemes.dark.node.accentText,
        tableSelectedBg: canvasThemes.dark.node.accentSoft,
        tableSelectedHoverBg: "rgba(251,146,60,.24)",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "infinite-canvas-dark" : "infinite-canvas-light" },
        token: {
            fontFamily: '"Baloo 2", "Resource Han Rounded SC", "Yuanti SC", "YouYuan", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif',
            fontSize: 14,
            fontSizeSM: 13,
            fontSizeLG: 16,
            borderRadius: 8,
            borderRadiusSM: 6,
            borderRadiusLG: 12,
            borderRadiusXS: 4,
            colorPrimary: color.brand,
            colorPrimaryHover: color.brandHover,
            colorPrimaryActive: color.brandActive,
            colorInfo: color.info,
            colorSuccess: color.success,
            colorWarning: color.warning,
            colorError: color.error,
            colorLink: color.brand,
            colorLinkHover: color.brandHover,
            colorLinkActive: color.brandActive,
            colorTextLightSolid: color.onBrand,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            colorTextTertiary: color.textTertiary,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBgElevated: color.elevatedBg,
            colorBorder: color.border,
            colorBorderSecondary: color.borderSecondary,
            controlItemBgHover: color.itemHoverBg,
            controlItemBgActive: color.itemSelectedBg,
            controlItemBgActiveHover: color.itemSelectedHoverBg,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Dropdown: {
                colorBgElevated: color.elevatedBg,
                colorText: color.itemText,
                controlItemBgHover: color.itemHoverBg,
                controlItemBgActive: color.itemSelectedBg,
                controlItemBgActiveHover: color.itemSelectedHoverBg,
            },
            Menu: {
                popupBg: color.elevatedBg,
                itemActiveBg: color.itemSelectedBg,
                itemHoverBg: color.itemHoverBg,
                itemSelectedBg: color.itemSelectedBg,
                itemSelectedColor: color.itemSelectedText,
                darkPopupBg: neutral.dark.elevatedBg,
                darkItemHoverBg: neutral.dark.itemHoverBg,
                darkItemSelectedBg: neutral.dark.itemSelectedBg,
                darkItemSelectedColor: neutral.dark.itemSelectedText,
            },
            Select: {
                optionActiveBg: color.itemHoverBg,
                optionSelectedBg: color.itemSelectedBg,
                optionSelectedColor: color.itemSelectedText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
